#!/usr/bin/env bash
# ===================
# functions by Jules CARAMELLE (julescaramelle@proton.me)
# ===================

function mkd() {
    mkdir -p "$@" && cd "$_";
}

function iut-ssh () {
    if test -z $1
then
    ssh jules.caramelle.etu@tp.iutinfo.fr
else
    if test "$1" = "tp.iutinfo.fr"
    then
    HOST="tp.iutinfo.fr"
    else
    HOST="${1}.iut-infobio.priv.univ-lille1.fr"
    fi
    if ping -c 1 $HOST >/dev/null 2>/dev/null
    then
        echo "Connecting to $HOST"
    else
        echo "iut-ssh: Can't resolve \"${HOST}\", is the VPN on ?"
        return 1
    fi
    ssh jules.caramelle.etu@$HOST
fi 
}

function git-set-github() {
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        git config --local user.name "jules-caramelle"
        git config --local user.email "julescaramelle@proton.me"
    else
        echo "Erreur : vous n'êtes pas dans un projet Git."
        return 1
    fi
}

function git-set-univ() {
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        git config --local user.name "jules.caramelle.etu"
        git config --local user.email "jules.caramelle.etu@univ-lille.fr"
    else
        echo "Erreur : vous n'êtes pas dans un projet Git."
        return 1
    fi
}